$(document).ready(function(){
	$('#image-gallery').lightSlider({
		gallery:true,
		item:1,
		tumbItem:3,
		sliderMargin:0,
		speed:500,
		auto:true,
		loop:true,
		onSliderLoad:function(){
			$('#image-gallery').removeClass('cS-hidden');
		}
	});
});